myproject/petservicesproject/petservicesproject/urls.py
from django.contrib import admin
from django.urls import path
from mypetapp.views import Serviceview, SPRequestList, Servicedetail, SPServiceList, SPcreateservice, SPdetailservice, SPupdateservice, SPdeleteservice
from django.conf import settings
from django.conf.urls.static import static
from mypetapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('serviceview/', Serviceview.as_view(), name='serviceview'),
    path('filter/<str:location>', views.filterservicebylocation, name='filterbylocation'),
    path('search/', views.search, name='search'),
    path('register/', views.register, name='register'),
    path('login/', views.login, name='login'),
    path('home/', views.home, name='home'),
    path('aboutus/', views.aboutus, name='aboutus'),
    path('servicedetail/<int:pk>/', Servicedetail.as_view(), name='servicedetail'),
    path('addtocart/', views.addtocart, name='addtocart'),   
    path('viewcart/', views.viewcart, name='viewcart'),
    path('removefromcart/', views.removefromcart, name='removefromcart'),
    # path('booking/', views.booking, name='booking'),
    path('spbookingdecision/', views.spbookingdecision, name='spbookingdecision'),
    path('accept/', views.accept, name='accept'),
    path('reject/', views.reject, name='reject'),
    # path('checkbkstatus/', views.checkbkstatus, name='checkbkstatus'),
    path('summary/', views.summary, name='summary'),
    path('payment/', views.payment, name='payment'),
    path('paymentsuccess', views.paymentsuccess, name='paymentsuccess'),
    path('spservicelist/', SPServiceList.as_view(), name="spservicelist"),
    path('sprequestlist/', SPRequestList.as_view(), name="requestview"),
    path('spcreateservice/', SPcreateservice.as_view(),name="spcreateservice"),
    path('spupdateservice/<int:pk>/', SPupdateservice.as_view(),name="spupdateservice"),
    path('spdetailservice/<int:pk>/', SPdetailservice.as_view(),name='spdetailservice'),
    path('spdeleteservice/<int:pk>/', SPdeleteservice.as_view(),name='spdeleteservice'),
    path('logout', views.logout, name='logout'),  
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

myproject/petservicesproject/mypetapp/models.py
from django.db import models
from django.db.models import Manager 
from datetime import date, time, datetime


# Create your models here.

class Custommanager(models.Manager):     
    def filterdata(self, a):
        return super().get_queryset().filter(location=a)

class Service(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="media")
    description = models.CharField(max_length=250)
    category = models.CharField(max_length=50)
    provider = models.CharField(max_length=50)
    location = models.CharField(max_length=50, default='location')
    price = models.FloatField()
    duration = models.FloatField()
    rating = models.FloatField(default='3.0')
    review = models.CharField(max_length=100, default='review')
    additional_info = models.CharField(max_length=300, default='additional info')

    cserviceobj = Custommanager()
    objects = Manager()

    class Meta:
        db_table = 'service'

class User(models.Model):
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=50)
    password = models.CharField(max_length=500)    
    usertype = models.CharField(max_length=50)
    address_line1 = models.CharField(max_length=50)
    address_line2 = models.CharField(max_length=50, default='area')
    city = models.CharField(max_length=50, default='city')
    state = models.CharField(max_length=50, default='state')
    pincode = models.BigIntegerField()
    contact = models.BigIntegerField()

    class Meta:
        db_table = 'user'

class SPService(models.Model):
    name = models.CharField(max_length=100)
    image = models.ImageField(upload_to="media")
    description = models.CharField(max_length=250)
    category = models.CharField(max_length=50)
    provider = models.CharField(max_length=50)
    location = models.CharField(max_length=50, default='location')
    price = models.FloatField()
    duration = models.FloatField()   
    status = models.CharField(max_length=50, default='pending')
    rating = models.FloatField(default='3.0')
    review = models.CharField(max_length=100, default='review')
    additional_info = models.CharField(max_length=300, default='additional info')
  
    
    cspserviceobj = Custommanager()
    objects = Manager()

    class Meta:
        db_table = 'spservice'


class cart(models.Model):
    user_id = models.ForeignKey(User, on_delete=models.CASCADE)
    service_id = models.ForeignKey(SPService, on_delete=models.CASCADE)
    service_date = models.DateField()
    service_time = models.TimeField()
    totalamount = models.FloatField()
    status = models.CharField(max_length=50, default='pending') 
    

    class Meta:
        db_table='cart'

class Booking(models.Model):        
    booking_number = models.CharField(max_length=100)
    booking_date = models.DateField(auto_now=True)
    booking_time = models.TimeField(auto_now=True)
    booking_status = models.CharField(max_length=100, default='pending') 
    cart_id = models.ForeignKey(cart, on_delete=models.CASCADE, default="")      

    class Meta:
        db_table = 'booking'

class Order(models.Model):
    ordernumber = models.CharField(max_length=100)
    orderdate = models.DateField(max_length=50)
    firstname = models.CharField(max_length=50)
    lastname = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    state = models.CharField(max_length=50)
    city = models.CharField(max_length=50)
    phonenumber = models.BigIntegerField()
    pincode = models.BigIntegerField()
    orderstatus = models.CharField(max_length=50)

    class Meta:
        db_table = 'order'

class Payment(models.Model):
    userid = models.ForeignKey(User, on_delete=models.CASCADE)
    orderid = models.ForeignKey(Order, on_delete=models.CASCADE)
    paymentmode = models.CharField(max_length=100, default='paypal')
    paymentstatus = models.CharField(max_length=100, default='pending')
    transactionid = models.CharField(max_length=200)    

    class Meta:
        db_table = 'payment'

class Orderdetail(models.Model):    
    ordernumber = models.CharField(max_length=100)
    userid = models.ForeignKey(User, on_delete=models.CASCADE)
    serviceid = models.ForeignKey(SPService, on_delete=models.CASCADE)   
    totalprice = models.IntegerField()
    paymentid = models.ForeignKey(Payment, on_delete=models.CASCADE)
    created_at = models.DateField(auto_now=True)
    updated_at = models.DateField(auto_now=True)
    
    class Meta:
        db_table = 'orderdetail'

myproject/petservicesproject/mypetapp/forms.py
from django import forms
from .models import SPService

class createform(forms.ModelForm):
    class Meta:
        model = SPService
        fields = ['name', 'image', 'description', 'category', 'provider', 'location', 'price', 'duration', 'status', 'additional_info']

myproject/petservicesproject/mypetapp/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Service, User, SPService, cart, Booking, Order, Payment, Orderdetail
from django.db.models import Q  
from django.contrib.auth.hashers import make_password, check_password
from .forms import createform
from django.urls import reverse_lazy
from django.http import JsonResponse
from datetime import date
from petservicesproject import settings
import razorpay


# Create your views here.

# class Serviceview(ListView):
#     model = Service
#     template_name = 'serviceview.html'
#     context_object_name = 'serviceobject'

#     def get_context_data(self, **kwargs):
#         data = self.request.session['sessionvalue']
#         context = super().get_context_data(**kwargs)
#         context['session'] = data
#         return context

class Serviceview(ListView):
    model = SPService
    template_name = 'serviceview.html'
    context_object_name = 'serviceobject'

    def get_context_data(self, **kwargs):
        data = self.request.session['sessionvalue']
        context = super().get_context_data(**kwargs)
        context['session'] = data
        return context

class SPServiceList(ListView):
    model = SPService
    template_name = 'spservicelist.html'
    context_object_name = 'spserviceobject'

    def get_context_data(self, **kwargs):
        data = self.request.session['sessionvalue']
        context = super().get_context_data(**kwargs)
        context['session'] = data
        return context

def filterservicebylocation(request, location):    
    serviceobjbylocation = SPService.cspserviceobj.filterdata(location)
    return render(request,'serviceview.html',{'serviceobject':serviceobjbylocation}) 

def search(request):
    if request.method == "POST":
        searchdata = request.POST.get('searchquery')
        serviceobject = SPService.objects.filter(Q(name__icontains =searchdata)|Q(description__icontains=searchdata))
        return render(request, 'serviceview.html', {'serviceobject': serviceobject})

def register(request):
    if request.method == "GET":
        return render(request, 'register.html')
    elif request.method == "POST":
        name = request.POST.get('name')
        email = request.POST.get('email')
        password = request.POST.get('password')
        epassword = make_password(password)
        usertype = request.POST.get('usertype')
        address_line1 = request.POST.get('address1')
        address_line2 = request.POST.get('address2')
        city = request.POST.get('city')
        state = request.POST.get('state')
        pincode = request.POST.get('pincode')
        contact = request.POST.get('contact')        
        userobject = User(name=name, email=email, password=epassword, usertype=usertype, address_line1=address_line1, address_line2=address_line2, city=city, state=state, pincode=pincode, contact=contact)
        print(userobject)
        userobject.save()
        return redirect('../login/')
    


def home(request):
    return render(request, 'home.html')

def aboutus(request):
    return render(request, 'aboutus.html')
    
def login(request):
    if request.method == "GET":
        return render(request, 'login.html')
    elif request.method == "POST":
        username = request.POST.get('email')
        password = request.POST.get('password')

        print(username, password)
        user = User.objects.filter(email = username)
        print("user: ", user)
        if user:
            userobject = User.objects.get(email = username)
            print("userobject: ", userobject)
            flag = check_password(password, userobject.password)
            print("flag", flag)
            if flag:
                request.session['sessionvalue'] = userobject.email
                usertype = userobject.usertype
                username = userobject.name
                if usertype == 'pet parent':
                    return redirect('../serviceview/')
                    # return render(request, 'beforeserviceview.html')
                else:
                    print('in else of flag')
                    spobj = SPService.objects.all()
                    # return render(request, 'spservicelist.html', {'spserviceobject':spobj, 'userobj': userobject})
                    return redirect('../spservicelist/')
            else:
                return render(request, 'login.html', {'message':'Incorrect username or password!'})
        else:
            return render(request, 'login.html', {'message':'Incorrect username or password!'})

# service provider service object class based views


class SPcreateservice(CreateView):
    model = SPService
    form_class = createform
    template_name = "spcreateservice.html"
    success_url = reverse_lazy('spservicelist')


class SPupdateservice(UpdateView):
    model = SPService
    form_class = createform
    template_name = 'spupdateservice.html'
    success_url = reverse_lazy('spservicelist')

class SPdetailservice(DetailView):
    model = SPService
    template_name = 'spservicedetail.html'
    context_object_name = 'i'

class SPdeleteservice(DeleteView):
    model = SPService
    template_name = 'spdeleteservice.html'
    success_url = reverse_lazy('spservicelist')

class SPRequestList(ListView):
    model = cart
    template_name = 'sprequestlist.html'
    context_object_name = 'cartobj'

    def get_context_data(self, **kwargs):
        data = self.request.session['sessionvalue']
        context = super().get_context_data(**kwargs)
        context['session'] = data
        return context

    # def get_context_data(self, **kwargs):
    #     context = super(SPRequestList, self).get_context_data(**kwargs)
    #     context['spserviceobj'] = SPService.objects.all()
    #     return context
    

# service provider service object class based views end

class Servicedetail(DetailView):
    model = SPService
    template_name = 'details.html'
    context_object_name = 'i'
    
    def get_context_data(self, **kwargs):
        data = self.request.session['sessionvalue']
        context = super().get_context_data(**kwargs)
        context['session'] = data
        return context

def addtocart(request):
    serviceid = request.POST.get("serviceid")
    usersession = request.session['sessionvalue']  # email of user
    date = request.POST.get('servicedate')
    time = request.POST.get('servicetime')
    userobj = User.objects.get(email = usersession) #fetch record from database table using email from session
    serviceobj = SPService.objects.get(id = serviceid)

    flag = cart.objects.filter(user_id = userobj.id, service_id = serviceobj.id)
    if flag:
        cartobj = cart.objects.get(user_id = userobj.id, service_id = serviceobj.id)    
        cartobj.date = date
        cartobj.time = time    
        cartobj.totalamount = serviceobj.price  
        cartobj.save()
    else:
        cartobj = cart(user_id = userobj, service_id = serviceobj, service_date = date, service_time = time, totalamount = serviceobj.price)
        cartobj.save()
    
    return redirect('../serviceview/')

def viewcart(request):   
    usersession = request.session['sessionvalue']  # email of user    
    userobj = User.objects.get(email = usersession)
    cartobj = cart.objects.filter(user_id = userobj.id)

    return render(request, 'cart.html', {'cartobj': cartobj, 'session': usersession})    

def removefromcart(request):
    useremail = request.session['sessionvalue']
    serviceid = request.POST.get('service_id')
    print(serviceid)
    userobj = User.objects.get(email = useremail)
    serviceobj = SPService.objects.get(id = serviceid)
    cartobj = cart.objects.get(user_id = userobj.id, service_id = serviceobj.id)

    if cartobj:
        cartobj.delete()
    return redirect('../viewcart/')

def summary(request):
    usersession = request.session['sessionvalue'] 
    userobj = User.objects.get(email = usersession)
    cartobj = cart.objects.filter(user_id = userobj.id, status = 'accepted')

    totalbill = 0
    count = 0
    for i in cartobj:
        totalbill = totalbill + i.totalamount
        count = count + 1    
    return render(request, 'summary.html' , {'session': usersession, 'totalbill': totalbill, 'cartobj': cartobj, 'count': count})


def payment(request):
    firstname = request.POST.get('fn')
    lastname = request.POST.get('ln')
    address = request.POST.get('address')
    state = request.POST.get('state')
    city = request.POST.get('city')
    pincode = request.POST.get('pin')
    phonenumber = request.POST.get('phone')
    datevar = date.today()
    orderobj = Order(firstname=firstname, lastname=lastname, address = address, state=state, city=city, pincode=pincode, phonenumber=phonenumber, orderdate=datevar, orderstatus = 'pending')
    orderobj.save()

    orderno = str(orderobj.id)+str(datevar).replace('-','')
    orderobj.ordernumber = orderno
    orderobj.save()
    print('orderobj: ', orderobj) 

    usersession = request.session['sessionvalue'] 
    print('usersession: ', usersession)
    userobj = User.objects.get(email = usersession)
    username = userobj.name
    cartobj = cart.objects.filter(user_id = userobj.id, status = 'accepted')
    print('cartobj: ', cartobj)

    totalbill = 0
    count = 0
    for i in cartobj:
        totalbill = totalbill + i.totalamount
        count = count + 1
            
    from django.core.mail import EmailMessage
    sm = EmailMessage('Order placed', 'Your order from the pet store app has been placed, total bill is '+str(totalbill), to=['samruddhiaware@gmail.com'])
    sm.send()

    # authorize razorpay client with API Keys.
    razorpay_client = razorpay.Client(
        auth=(settings.RAZORPAY_KEY_ID, settings.RAZORPAY_KEY_SECRET))
 

    currency = 'INR'
    amount = 20000  # Rs. 200
 
    # Create a Razorpay Order

myproject/petservicesproject/mypetapp/templates/booking.html
{% extends 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
    <style>
        body {
            background: url(../../media/backg3.jpg) no-repeat center fixed;
        }

        .ratings i {
            font-size: 16px;
            color: red
        }

        .strike-text {
            color: red;
            text-decoration: line-through
        }

        .product-image {
            width: 100%
        }

        .dot {
            height: 7px;
            width: 7px;
            margin-left: 6px;
            margin-right: 6px;
            margin-top: 3px;
            background-color: blue;
            border-radius: 50%;
            display: inline-block
        }

        .spec-1 {
            color: #938787;
            font-size: 15px
        }

        h5 {
            font-weight: 400
        }

        .para {
            font-size: 16px
        }

        .checked {
            color: orange;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {% block myblock %}
    <div class="container mt-5 mb-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-10">
                <div>
                    <div class="card text-center" style=" margin-bottom: 15px;">

                        <div class="card-body">
                            <h5 class="card-title">List of service bookings </h5>
                            {% for i in bookingobj %}


                            <div class="row p-2 bg-white border rounded" style="margin-bottom: 5px;">
                                <div>
                                    <h5>Booking no. {{i.booking_number}}</h5>
                                    <h5>Booking date. {{i.booking_date}}</h5>
                                    <h5>Booking time. {{i.booking_time}}</h5>
                                    <h5>Booking status. {{i.booking_status}}</h5>
                                </div>

                                <div class="col-md-3 mt-1">
                                    <img class="img-fluid img-responsive rounded product-image"
                                        src="{{i.cart_id.service_id.image.url}}">
                                </div>

                                <div class="col-md-6 mt-1">
                                    <h5>{{i.cart_id.service_id.name}}</h5>
                                    <div>
                                        <span style="font-size: x-small;">by</span>
                                        <span style="font-weight: bold;">{{i.cart_id.service_id.provider}}</span>
                                    </div>


                                    <div class="mt-1 mb-1 spec-1">

                                        <span>{{i.cart_id.service_id.category}}</span>
                                        <span class="dot">.</span>
                                        <span>{{i.cart_id.service_id.duration}}-min</span>
                                        <span class="dot">.</span>

                                    </div>
                                    <p class="text-justify text-truncate para mb-0">
                                        {{i.cart_id.service_id.description}}<br><br></p>

                                </div>

                                <div class="align-items-center align-content-center col-md-3 border-left mt-1">
                                    <div class="d-flex flex-row align-items-center">
                                        <h4 class="mr-1">Rs. {{i.cart_id.service_id.price}}</h4>
                                    </div>
                                    <p>
                                        <span>Rating: </span><span class="badge text-bg-info"
                                            style="background-color: yellowgreen">{{i.cart_id.service_id.rating}}/5</span>
                                    </p>
                                    <div class="d-flex flex-column mt-4">
                                        <div>
                                            <table>
                                                <tr>
                                                    <td>S.No.</td>
                                                    <td>Details</td>
                                                </tr>
                                                <tr>
                                                    <td>Date</td>
                                                    <td>{{i.cart_id.service_date}}</td>
                                                </tr>
                                                <tr>
                                                    <td>Time</td>
                                                    <td>{{i.cart_id.service_time}}</td>
                                                </tr>
                                                <tr>
                                                    <td>User</td>
                                                    <td>{{i.cart_id.user_id.name}}</td>
                                                </tr>

                                            </table>
                                        </div>

                                        <form action="{% url 'payment' %}" method="post" value="{{i.booking_number}}"
                                            name="bookingno">
                                            {% csrf_token %}
                                            <button type="submit">proceed to pay</button>
                                        </form>






                                    </div>

                                </div>
                            </div>
                            {% endfor %}

                        </div>

                    </div>

                </div>


            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

myproject/petservicesproject/mypetapp/templates/details.html
{% extends 'navbar.html' %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Services</title>
    <style>
        body {
            background: url(../../media/backg3.jpg) no-repeat center fixed;
        }

        .ratings i {
            font-size: 16px;
            color: red
        }

        .strike-text {
            color: red;
            text-decoration: line-through
        }

        .product-image {
            width: 100%
        }

        .dot {
            height: 7px;
            width: 7px;
            margin-left: 6px;
            margin-right: 6px;
            margin-top: 3px;
            background-color: blue;
            border-radius: 50%;
            display: inline-block
        }

        .spec-1 {
            color: #938787;
            font-size: 15px
        }

        h5 {
            font-weight: 400
        }

        .para {
            font-size: 16px
        }

        .checked {
            color: orange;
        }
    </style>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.4.1/dist/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>

<body>
    {% block myblock %}
    <div class="container mt-5 mb-5">
        <div class="d-flex justify-content-center row">
            <div class="col-md-10">

                <div class="row p-3 bg-white border rounded" style="margin-bottom: 5px;">

                    <div class="col-md-3 mt-1">
                        <img class="img-fluid img-responsive rounded product-image" src="{{i.image.url}}">
                    </div>

                    <div class="col-md-6 mt-2" style="padding-left: 20px; margin-top: 10px ;">
                        <h5>{{i.name}}</h5>
                        <div>
                            <span style="font-size: x-small;">by</span>
                            <span style="font-weight: bold; color:blue;">{{i.provider}}</span>
                        </div>
                        <div>
                            <br>
                        </div>
                        <div class="mt-1 mb-1 spec-1" style="font-weight: bold;">
                            <span>{{i.category}}</span>
                            <span class="dot">.</span>
                            <span>{{i.duration}}-min</span>
                            <span class="dot">.</span>
                        </div>

                        <div class="mt-1 mb-1 spec-1">
                            <span>{{i.description}}</span>
                            <span class="dot">.</span>
                        </div>
                        <br>
                        <p>
                            <span>Rating: </span><span class="badge text-bg-info"
                                style="background-color: yellowgreen">{{i.rating}}/5</span>
                        </p>
                        <p>
                            <span>Review: </span><span>{{i.review}}</span>
                        </p>
                        <p>
                            <span>Additional info: </span><span>{{i.additional_info}}</span>
                        </p>



                    </div>

                    <div class="col-md-3 border-left" style="align-content:center; padding-left: 35px; padding-right: 35px;">

                        <h4 class="mr-1">Rs. {{i.price}}</h4>
                        <!-- <p>
                            <span>Rating: </span><span class="badge text-bg-info" style="background-color: yellowgreen">{{i.rating}}/5</span>
                        </p> -->
                        <form action="{% url 'addtocart' %}" method="POST">
                            {% csrf_token %}

                            <label for="servicedate" >Select date:</label>
                            <input type="date" id="servicedate" name="servicedate"  min="2024-07-08">
                            <label for="servicetime" >Select time:</label>
                            <input type="time" id="servicetime" name="servicetime">
                            <input type="hidden" name="serviceid" value="{{i.id}}">
                            <button class="btn btn-outline-primary btn-sm mt-2" type="submit">Add to cart</button>


                        </form>



                    </div>

                </div>

            </div>
        </div>
    </div>
    {% endblock %}
</body>

</html>

myproject/petservicesproject/mypetapp/templates/service_search.html
<!DOCTYPE html>
<html>
<head>
    <title>Search Services</title>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
</head>
<body>
    <h1>Search Services</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Search</button>
    </form>

    <script type="text/javascript">
        $("#id_state").change(function () {
            var url = "{% url 'load_cities' %}";
            var stateId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'state': stateId
                },
                success: function (data) {
                    $("#id_city").html('<option value="">Select City</option>');
                    $.each(data, function (key, value) {
                        $("#id_city").append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                }
            });
        });

        $("#id_city").change(function () {
            var url = "{% url 'load_areas' %}";
            var cityId = $(this).val();
            $.ajax({
                url: url,
                data: {
                    'city': cityId
                },
                success: function (data) {
                    $("#id_area").html('<option value="">Select Area</option>');
                    $.each(data, function (key, value) {
                        $("#id_area").append('<option value="' + value.id + '">' + value.name + '</option>');
                    });
                }
            });
        });
    </script>
</body>
</html>